name: Cypress & Vitest Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  install-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        id: npm-cache
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies if cache invalid
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
  cypress-run:
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore npm dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cypress run
        env:
          CYPRESS_TEST_BORROWER_PUBLIC_KEY: ${{ secrets.TEST_BORROWER_PUBLIC_KEY }}
          CYPRESS_TEST_VAULT_PUBLIC_KEY: ${{ secrets.TEST_VAULT_PUBLIC_KEY }}
          CYPRESS_YUSDC_ISSUER: ${{ secrets.YUSDC_ISSUER_PUBLIC_KEY }}
          VITE_YUSDC_ISSUER_PUBLIC_KEY: ${{ secrets.YUSDC_ISSUER_PUBLIC_KEY }}
          VITE_YUSDC_ISSUER_SECRET_KEY: ${{ secrets.YUSDC_ISSUER_SECRET_KEY }}
          VITE_PUSD_ISSUER_PUBLIC_KEY: ${{ secrets.PUSD_ISSUER_PUBLIC_KEY }}
        uses: cypress-io/github-action@v4.2.0
        with:
          build: npm run build
          start: npm run dev
  test:
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Restore npm dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Run the tests
        run: |
          npm install
          npm run test
  build-and-deploy:
    needs: [cypress-run, test]
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install and Build
        env:
          VITE_YUSDC_ISSUER_PUBLIC_KEY: ${{ secrets.YUSDC_ISSUER_PUBLIC_KEY }}
          VITE_YUSDC_ISSUER_SECRET_KEY: ${{ secrets.YUSDC_ISSUER_SECRET_KEY }}
          VITE_PUSD_ISSUER_PUBLIC_KEY: ${{ secrets.PUSD_ISSUER_PUBLIC_KEY }}
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: dist
